2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Configure stats pid to 24728
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lathw\.config\wandb\settings
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\settings
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_init.py:_log_setup():526] Logging user logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_222322-ujgjwc4d\logs\debug.log
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_init.py:_log_setup():527] Logging internal logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_222322-ujgjwc4d\logs\debug-internal.log
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000023B96A3C110>
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_init.py:init():566] calling init triggers
2024-03-08 22:23:22,969 INFO    MainThread:24728 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-08 22:23:22,974 INFO    MainThread:24728 [wandb_init.py:init():616] starting backend
2024-03-08 22:23:22,974 INFO    MainThread:24728 [wandb_init.py:init():620] setting up manager
2024-03-08 22:23:22,982 INFO    MainThread:24728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-08 22:23:22,989 INFO    MainThread:24728 [wandb_init.py:init():628] backend started and connected
2024-03-08 22:23:22,999 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-08 22:23:23,000 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-08 22:23:23,000 INFO    MainThread:24728 [wandb_init.py:init():720] updated telemetry
2024-03-08 22:23:23,579 INFO    MainThread:24728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-08 22:23:25,233 ERROR   MainThread:24728 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-03-08 22:23:26,127 ERROR   MainThread:24728 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-03-08 22:24:11,573 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-08 22:24:11,573 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Configure stats pid to 24728
2024-03-08 22:24:11,573 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lathw\.config\wandb\settings
2024-03-08 22:24:11,573 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\settings
2024-03-08 22:24:11,573 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-08 22:24:11,573 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_init.py:_log_setup():526] Logging user logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_222411-18sxctmw\logs\debug.log
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_init.py:_log_setup():527] Logging internal logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_222411-18sxctmw\logs\debug-internal.log
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_init.py:init():566] calling init triggers
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_init.py:init():616] starting backend
2024-03-08 22:24:11,588 INFO    MainThread:24728 [wandb_init.py:init():620] setting up manager
2024-03-08 22:24:11,599 INFO    MainThread:24728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-08 22:24:11,599 INFO    MainThread:24728 [wandb_init.py:init():628] backend started and connected
2024-03-08 22:24:11,609 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-08 22:24:11,609 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-08 22:24:11,609 INFO    MainThread:24728 [wandb_init.py:init():720] updated telemetry
2024-03-08 22:24:11,655 INFO    MainThread:24728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-08 22:25:42,137 ERROR   MainThread:24728 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:25:42,372 ERROR   MainThread:24728 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:42:58,027 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-08 22:42:58,027 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Configure stats pid to 24728
2024-03-08 22:42:58,027 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lathw\.config\wandb\settings
2024-03-08 22:42:58,027 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\settings
2024-03-08 22:42:58,027 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-08 22:42:58,028 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-08 22:42:58,028 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-08 22:42:58,028 INFO    MainThread:24728 [wandb_init.py:_log_setup():526] Logging user logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_224257-sbb56ond\logs\debug.log
2024-03-08 22:42:58,028 INFO    MainThread:24728 [wandb_init.py:_log_setup():527] Logging internal logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_224257-sbb56ond\logs\debug-internal.log
2024-03-08 22:42:58,028 INFO    MainThread:24728 [wandb_init.py:init():566] calling init triggers
2024-03-08 22:42:58,029 INFO    MainThread:24728 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-08 22:42:58,029 INFO    MainThread:24728 [wandb_init.py:init():616] starting backend
2024-03-08 22:42:58,029 INFO    MainThread:24728 [wandb_init.py:init():620] setting up manager
2024-03-08 22:42:58,047 INFO    MainThread:24728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-08 22:42:58,047 INFO    MainThread:24728 [wandb_init.py:init():628] backend started and connected
2024-03-08 22:42:58,063 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-08 22:42:58,063 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-08 22:42:58,063 INFO    MainThread:24728 [wandb_init.py:init():720] updated telemetry
2024-03-08 22:42:58,489 INFO    MainThread:24728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-08 22:44:29,064 ERROR   MainThread:24728 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:44:30,039 ERROR   MainThread:24728 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:44:35,119 WARNING MsgRouterThr:24728 [router.py:message_loop():77] message_loop has been closed
2024-03-08 22:45:11,053 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-08 22:45:11,053 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Configure stats pid to 24728
2024-03-08 22:45:11,053 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lathw\.config\wandb\settings
2024-03-08 22:45:11,053 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\settings
2024-03-08 22:45:11,054 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-08 22:45:11,054 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_init.py:_log_setup():526] Logging user logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_224511-d6v8mgix\logs\debug.log
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_init.py:_log_setup():527] Logging internal logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_224511-d6v8mgix\logs\debug-internal.log
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_init.py:init():566] calling init triggers
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_init.py:init():616] starting backend
2024-03-08 22:45:11,055 INFO    MainThread:24728 [wandb_init.py:init():620] setting up manager
2024-03-08 22:45:11,063 INFO    MainThread:24728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-08 22:45:11,063 INFO    MainThread:24728 [wandb_init.py:init():628] backend started and connected
2024-03-08 22:45:11,071 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-08 22:45:11,071 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-08 22:45:11,072 INFO    MainThread:24728 [wandb_init.py:init():720] updated telemetry
2024-03-08 22:45:11,121 INFO    MainThread:24728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-08 22:46:41,698 ERROR   MainThread:24728 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:46:41,910 ERROR   MainThread:24728 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:51:13,351 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-08 22:51:13,351 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Configure stats pid to 24728
2024-03-08 22:51:13,351 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lathw\.config\wandb\settings
2024-03-08 22:51:13,351 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\settings
2024-03-08 22:51:13,351 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-08 22:51:13,351 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-08 22:51:13,375 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-08 22:51:13,376 INFO    MainThread:24728 [wandb_init.py:_log_setup():526] Logging user logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_225113-jqwde3wd\logs\debug.log
2024-03-08 22:51:13,376 INFO    MainThread:24728 [wandb_init.py:_log_setup():527] Logging internal logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_225113-jqwde3wd\logs\debug-internal.log
2024-03-08 22:51:13,376 INFO    MainThread:24728 [wandb_init.py:init():566] calling init triggers
2024-03-08 22:51:13,376 INFO    MainThread:24728 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-08 22:51:13,377 INFO    MainThread:24728 [wandb_init.py:init():616] starting backend
2024-03-08 22:51:13,377 INFO    MainThread:24728 [wandb_init.py:init():620] setting up manager
2024-03-08 22:51:13,383 INFO    MainThread:24728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-08 22:51:13,384 INFO    MainThread:24728 [wandb_init.py:init():628] backend started and connected
2024-03-08 22:51:13,396 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-08 22:51:13,396 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-08 22:51:13,396 INFO    MainThread:24728 [wandb_init.py:init():720] updated telemetry
2024-03-08 22:51:13,463 INFO    MainThread:24728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-08 22:52:44,100 ERROR   MainThread:24728 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:52:44,302 ERROR   MainThread:24728 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:53:11,201 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-08 22:53:11,201 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Configure stats pid to 24728
2024-03-08 22:53:11,203 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lathw\.config\wandb\settings
2024-03-08 22:53:11,203 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\settings
2024-03-08 22:53:11,203 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-08 22:53:11,203 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-08 22:53:11,204 INFO    MainThread:24728 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-08 22:53:11,204 INFO    MainThread:24728 [wandb_init.py:_log_setup():526] Logging user logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_225311-v3xzq4xd\logs\debug.log
2024-03-08 22:53:11,205 INFO    MainThread:24728 [wandb_init.py:_log_setup():527] Logging internal logs to d:\Engineering\ENTC\Final Year Project\Project\Deep-Learning-for-End-to-End-Over-the-Air-Communications\Lathika\wandb\run-20240308_225311-v3xzq4xd\logs\debug-internal.log
2024-03-08 22:53:11,205 INFO    MainThread:24728 [wandb_init.py:init():566] calling init triggers
2024-03-08 22:53:11,205 INFO    MainThread:24728 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-08 22:53:11,205 INFO    MainThread:24728 [wandb_init.py:init():616] starting backend
2024-03-08 22:53:11,205 INFO    MainThread:24728 [wandb_init.py:init():620] setting up manager
2024-03-08 22:53:11,214 INFO    MainThread:24728 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-08 22:53:11,215 INFO    MainThread:24728 [wandb_init.py:init():628] backend started and connected
2024-03-08 22:53:11,228 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-08 22:53:11,228 INFO    MainThread:24728 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-08 22:53:11,228 INFO    MainThread:24728 [wandb_init.py:init():720] updated telemetry
2024-03-08 22:53:11,318 INFO    MainThread:24728 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-08 22:54:41,964 ERROR   MainThread:24728 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 22:54:42,201 ERROR   MainThread:24728 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\lathw\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-08 23:08:28,280 WARNING MsgRouterThr:24728 [router.py:message_loop():77] message_loop has been closed
2024-03-09 01:54:27,827 WARNING MsgRouterThr:24728 [router.py:message_loop():77] message_loop has been closed
